[package]
name = "system_info"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.160", features = ["derive"]}
serde_json = "1.0.96"
systemstat = "0.2.3"
home = "0.5.4"
