[workspace]
members = ["carburetor", "cockpit/src-tauri", "common", "common/message_derive"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = [
    "Koen Westendorp <koensswestendorp@gmail.com>",
    "Bauke Westendorp <baukewestendorp@gmail.com>",
]
