[linkage_lib]
address = { host = "0.0.0.0", port = 12362 }

[runtime]
port = 8009
linkage_lib_entry_point = "PLACEHOLDER"

[carburetor]
port = 48862

[cockpit_backend]
port = 3013
runtime_address = { host = "0.0.0.0", port = 8009 }
linkage_lib_address = { host = "0.0.0.0", port = 12362 }
