# This is an example of the optional configuration file in ~/.config/linkage/config.toml

[linkage_lib]
# The port on which Linkage-lib will listen
port = 12362
# The address Carburetor is listening on
carburetor_address = { host = "0.0.0.0", port = 48862 }
# The port on which the logger will send data
logger_port = 7640

[carburetor]
# The port on which Carburetor will listen
port = 48862
# The port on which the logger will send data
logger_port = 7644

[gauge]
# The port on which Gauge will listen
port = 4226

[cockpit]
# The address the Linkage-lib socket service that starts Linkage-lib is listening on
linkage_socket_address = { host = "raspberrypi.local", port = 9999 }
# The address Linkage-lib is listening on
linkage_lib_address = { host = "raspberrypi.local", port = 12362 }

# The address the Cockpit-backend logger is listening on
cockpit_backend_logger_address = { host = "0.0.0.0", port = 7642 }
# The address the Linkage-lib logger is listening on
linkage_lib_logger_address = { host = "raspberrypi.local", port = 7640 }
# The address the Carburetor logger is listening on
carburetor_logger_address =  { host = "raspberrypi.local", port = 7644 }