[package]
name = "carburetor"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
simple-signal = "1.1.1"
sys-info = "0.9.1"
common = { path = "../common" }

[target.'cfg(target_arch = "armv7")'.dependencies]
rppal = "0.14.1"
