[linkage_lib]
carburetor_address = { host = "0.0.0.0", port = 48862 }
port = 12362

[runtime]
port = 8009
linkage_lib_entry_point = "/home/pi/robot_code/build/main.js"
node_path = "/usr/bin/node"
carburetor_path = "/home/pi/linkage/target/release/carburetor"

[carburetor]
port = 48862

[cockpit_backend]
port = 3012
runtime_address = { host = "0.0.0.0", port = 8009 }
linkage_lib_address = { host = "0.0.0.0", port = 12362 }
