[linkage_lib]
port = 12362
carburetor_address = { host = "raspberrypi.local", port = 48862 }

[carburetor]
port = 48862

[cockpit]
linkage_socket_address = { host = "raspberrypi.local", port = 9999 }
linkage_lib_address = { host = "raspberrypi.local", port = 12362 }
linkage_lib_logger_address = { host = "raspberrypi.local", port = 7640 }
