[package]
name = "cockpit-backend"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
gilrs = "0.10.1"
simple-signal = "1.1.1"
ws = "0.9.2"
common = { path = "../../common" }
