[package]
name = "cockpit-backend"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
common = { path = "../../common" }
gilrs = "0.10.1"
log = "0.4.17"
bus = "2.4.0"
websocket = "0.26.5"
