[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { version = "0.13.3", features = ["toml"] }
serde = "1.0.152"
xdg = "2.4.1"
message_derive = { path = "message_derive" }
log = "0.4.17"
fern = "0.6.2"
ws = "0.9.2"
bus = "2.4.0"
serde_json = "1.0.95"
systemstat = "0.2.3"
home = "0.5.4"
