[package]
name = "common"
version = "0.1.0"
edition = "2021"

[features]
messages = ["dep:message_derive"]

[dependencies]
config = { path = "config", optional = true }
message_derive = { path = "message_derive", optional = true }