name: check

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

# Spend CI time only on latest ref: https://github.com/jonhoo/rust-ci-conf/pull/5
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    name: check fmt | ${{ matrix.toolchain }} / fmt

    strategy:
      matrix:
        toolchain: [ stable ]

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt

      - name: cargo fmt --check
        run: cargo fmt --check

  clippy:
    name: check clippy | rust ${{ matrix.toolchain }} / clippy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write

    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, beta]

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: install dependencies
        run: >-
          sudo apt-get update &&
          sudo apt-get install -y
          libgtk-3-dev
          libayatana-appindicator3-dev
          libwebkit2gtk-4.0-dev
          libudev-dev

      - name: create dist folder for tauri
        run: mkdir -p ${{ github.workspace }}/cockpit/dist

      - name: install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy

      - name: cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  doc:
    runs-on: ubuntu-latest
    name: check doc | rust nightly / doc

    strategy:
      matrix:
        toolchain: [ nightly ]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - run: >-
          sudo apt-get update &&
          sudo apt-get install -y
          libgtk-3-dev
          libayatana-appindicator3-dev
          libwebkit2gtk-4.0-dev
          libudev-dev

      - name: create dist folder for tauri
        run: mkdir -p ${{ github.workspace }}/cockpit/dist

      - name: install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: cargo doc
        run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: --cfg docsrs
