name: publish | cockpit

on:
  push:
    tags:
      - "cockpit-v*.*.*"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-cockpit:
    runs-on: ${{ matrix.platform }}

    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-20.04 ]
        node: [ 16 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: >-
          sudo apt-get update &&
          sudo apt-get install -y 
          libgtk-3-dev 
          libwebkit2gtk-4.0-dev 
          libappindicator3-dev
          librsvg2-dev 
          patchelf
          libudev-dev

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - name: Install frontend dependencies
        run: pnpm install

      - name: Release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'Cockpit v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false