name: publish | parts

on:
  push:
    tags:
      - "parts-v*.*.*"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-parts:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    strategy:
      matrix:
        include:
          - build: arm-v7
            os: ubuntu-latest
            rust: stable
            target: armv7-unknown-linux-gnueabihf
            linker: gcc-arm-linux-gnueabihf
            container: rust # Needed for the correct version of glibc
            cross: true

    steps:
      - name: Install sudo package
        run: apt update && apt install -y sudo

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.rustup
            target
          key: ${{ runner.os }}-${{ matrix.rust }}

      - name: Install Linker
        if: matrix.cross
        run: |
          sudo apt update
          sudo apt install -y ${{ matrix.linker }}

      - name: Install Rust
        run: |
          rustup install ${{ matrix.rust }}
          rustup target add ${{ matrix.target }}
          rustup show

      - name: Build Gauge
        run: cargo build -p gauge --release --target ${{ matrix.target }}

      - name: Build Carburetor
        run: cargo build -p carburetor --release --target ${{ matrix.target }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: 'Parts ${{ github.ref }}'
          body: 'These executables are used by the Linkage installation on the Raspberry Pi.'
          draft: true
          prerelease: false
          files: |
            target/${{ matrix.target }}/release/gauge
            target/${{ matrix.target }}/release/carburetor

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}