name: Rust

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    name: 'Clippy Check'
    steps:
      - uses: actions/checkout@v3

      - name: Cache Rust files
        uses: Swatinem/rust-cache@v2

      - name: Install dependencies
        run: >-
          sudo apt-get update &&
          sudo apt-get install -y
          libgtk-3-dev
          libayatana-appindicator3-dev
          libwebkit2gtk-4.0-dev
          libudev-dev

      - name: Create dist folder for Tauri
        run: mkdir -p ${{ github.workspace }}/cockpit/dist

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
