name: Rust

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: 'sudo apt update && sudo apt install
          libwebkit2gtk-4.0-dev
          build-essential
          curl
          wget
          libglib2.0-dev
          libssl-dev
          libgtk-3-dev
          libappindicator3-dev
          librsvg2-dev
          libappindicator-dev
          libgdk3.0-cil libatk1.0-dev'
      - name: Lint
        run: cargo clippy --verbose
